const SET_ORDER = 'SET_ORDER';
const SET_ORDERS = 'SET_ORDERS';
const GET_ORDERS = 'GET_ORDERS';
const DELETE_ORDER = 'DELETE_ORDER';
const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';

export {
        SET_ORDER,
        SET_ORDERS,
        GET_ORDERS,
        DELETE_ORDER,
        UPDATE_ORDER_STATUS,
        SHOW_LOADING,
        HIDE_LOADING,
}
