const SET_ORDER = 'SET_ORDER';
const SET_ORDERS = 'SET_ORDERS';
const GET_ORDERS = 'GET_ORDERS';
const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
const DELETE_ORDER = 'DELETE_ORDER';
const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
const SET_ORDERS_PAGINATION = 'SET_ORDERS_PAGINATION';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';

export {
  SET_ORDER,
  SET_ORDERS,
  GET_ORDERS,
  GET_ORDER_BY_ID,
  DELETE_ORDER,
  UPDATE_ORDER_STATUS,
  SET_ORDERS_PAGINATION,
  SHOW_LOADING,
  HIDE_LOADING
};
