const LOGIN_USER = 'LOGIN_USER';
const SET_AUTH = 'SET_AUTH';
const LOGOUT_USER = 'LOGOUT_USER';
const UPDATE_USER_BY_TOKEN = 'UPDATE_USER_BY_TOKEN';
const CHECK_USER_BY_TOKEN = 'CHECK_USER_BY_TOKEN';
const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
const SET_LOADING = 'SET_LOADING';

export {
    LOGIN_USER,
    SET_AUTH,
    LOGOUT_USER,
    CHECK_USER_BY_TOKEN,
    SET_AUTH_ERROR,
    SET_LOADING,
    UPDATE_USER_BY_TOKEN,
}
