const SET_PRODUCT = 'SET_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
const ADD_PRODUCT = 'ADD_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';

export {
        SET_PRODUCT,
        SET_PRODUCTS,
        GET_PRODUCTS,
        GET_PRODUCT_BY_ID,
        ADD_PRODUCT,
        UPDATE_PRODUCT,
        DELETE_PRODUCT,
        SHOW_LOADING,
        HIDE_LOADING,
}
