const UPLOAD_IMAGE_TO_CLOUD = 'UPLOAD_IMAGE_TO_CLOUD';
const DELETE_IMAGES_FROM_CLOUD = 'DELETE_IMAGES_FROM_CLOUD';
const SET_IMAGE_TO_PRODUCT = 'SET_IMAGE_TO_PRODUCT';
const SET_ALL_IMAGES_TO_PRODUCT = 'SET_ALL_IMAGES_TO_PRODUCT';
const SET_IMAGE_TO_SLIDER = 'SET_IMAGE_TO_SLIDER';
const SET_IMAGE_TO_DELETE_AND_UPDATE_STATE = 'SET_IMAGE_TO_DELETE_AND_UPDATE_STATE';
const CLEAR_IMAGES_STATE = 'CLEAR_IMAGES_STATE';
const SET_IMAGE_LOADING = 'SET_IMAGE_LOADING';
const SET_SLIDER_IMAGE_LOADING = 'SET_SLIDER_IMAGE_LOADING';

export {
    UPLOAD_IMAGE_TO_CLOUD,
    DELETE_IMAGES_FROM_CLOUD,
    SET_IMAGE_TO_PRODUCT,
    SET_ALL_IMAGES_TO_PRODUCT,
    SET_IMAGE_TO_SLIDER,
    SET_IMAGE_TO_DELETE_AND_UPDATE_STATE,
    CLEAR_IMAGES_STATE,
    SET_IMAGE_LOADING,
    SET_SLIDER_IMAGE_LOADING,
}
