const UPLOAD_IMAGE_TO_CLOUD = 'UPLOAD_IMAGE_TO_CLOUD';
const DELETE_IMAGE_FROM_CLOUD = 'DELETE_IMAGE_FROM_CLOUD';
const SET_IMAGE_TO_PRODUCT = 'SET_IMAGE_TO_PRODUCT';
const SET_ALL_IMAGES_TO_PRODUCT = 'SET_ALL_IMAGES_TO_PRODUCT';
const SET_IMAGE_TO_SLIDER = 'SET_IMAGE_TO_SLIDER';
const SET_IMAGE_TO_DELETE_AND_UPDATE_STATE = 'SET_IMAGE_TO_DELETE_AND_UPDATE_STATE';
const CLEAR_UPLOAD_STATE = 'CLEAR_UPLOAD_STATE';
const SET_LOADING = 'SET_LOADING';

export {
    UPLOAD_IMAGE_TO_CLOUD,
    DELETE_IMAGE_FROM_CLOUD,
    SET_IMAGE_TO_PRODUCT,
    SET_ALL_IMAGES_TO_PRODUCT,
    SET_IMAGE_TO_SLIDER,
    SET_IMAGE_TO_DELETE_AND_UPDATE_STATE,
    CLEAR_UPLOAD_STATE,
    SET_LOADING,
}
